
## Title
 Good afternoon, RMed. My name is Kyle Grealis, and today I am presenting the sumExtras package for streamlining table workflows in clinical research with R.

## Intro
sumExtras is a R CRAN package created to enhance my workflows with gtsummary. 
Now, I *love* gtsummary and it has been my go-to table-making package for a while now. 
The output tables are elegant, clean and readable. 
But oftentimes i would rewrite the same bits of code over and over. 
And when you do that, we're advised it's best to write a function -- don't repeat yourself, right?
So I wrote a few wrapper functions. And then I was writing the same wrapper functions in multiple projects.
Ah yes, it was time to convert these repeatable lines of code to a package!
Simply put: sumExtras is a group of extra functions for using gtsummary tables.

## The plan [incremental]
Today we will learn:
* how to  apply a JAMA-ready table style theme
* customize missing values using the clean table function
* learn the power of the extras function
* quickly apply automatic variable labeling
* group like-variables and [CLICK] apply font styling & background colors to those group headers
* We will do this while progressively building our code pipeline.

## What we'll build
The final table we build today will look like this, and I will demonstrate how to 
reduce our lines of code while adding custom table styling bits throughout. 
Let's offer bespoke tables to our colleagues and fellow stakeholders!

## Creating a summary table
The gtsummary package provides the trial dataset, complete with synthetic information
of 200 patients who received one of two treatment drugs. Notice the data is...
not what we normally receive!
Here we have complete records, but let's make this more real-world in order to 
visualize other features available with sumExtras. 

## 
We'll begin by mutating our data, replacing the values for marker and grade [CLICK]
with zeroes and NA values when the treatment drug is B. 
We'll save this as a new dataset, "dat". [CLICK]
Notice on line 17 the 0 and NA values for marker & grade, respectively.

## Initial gtsummary table
Our initial gtsummary table is packed with great output. 
It's beautiful and has a clean font making it easily readable.
The statistics are nicely grouped and this immediately is a tremendous improvement
over shipping generic console output to your PIs.
We can begin to improve this table by

## Setting a theme
...setting a theme. I've often reached for the JAMA theme because it takes the
initial table and makes it nice and compact. 
sumExtras provides the use_jama_theme function you can set once at the top of your
code to use for every table.
[CLICK]
You can see that this is nothing more than reducing how much code I needed to 
remember... it's a wrapper around an existing gtsummary function.


## Cleaning the table
So we made a nicely-themed, more compact table. 
However, we have zeros and missing values clogging up real estate.
[CLICK]
Let's set a goal to replace the all-zero and all-NA filled cells. 
Perhaps we can remove some noise and direct the attention to the non-missingness
of our data.

## Cleaning the table
When we pipe our table code to clean_table, we replace the cells that have
mean & standard deviation values of all-zero or counts cells of zero with NA percentage
with a cleaner emdash. 
This is a default replacement placeholder that you can adjust... you can even use an emoji if you'd like.
If you compare the left & right output for Drug B, I find that my attention is now drawn to what truly matters.
This effect is more noticeable with more amount of missingness.

## Adding labels...
This output is closer to our final table and more of what I want.
[CLICK]
The header "Characteristic" has been removed
[CLICK]
I've added a p-value column on the right of the table
[CLICK]
The variable labels and significant p-values are now bolded
[CLICK]
An Overall column has been added to the first output column position
[CLICK]
And lastly the clean table function has replace the noise of missingness 
as we've just seen with clean table.

[quick pause]
[CLICK]
The same table was created with these code cells
all while replacing the bottom six lines of code on the left 
[CLICK]
with one pipe to extras on the right!
Another feature of sumExtras is how we can reduce redundancies with labeling.

## Labeling hierarchy
Using gtsummary and sumExtras requires a small bit of understanding labeling hierarchy
[CLICK]
First, using gtsummary's label parameter ALWAYS wins
[CLICK]
Next, if our data contains variable label attributes, those are second in order
[CLICK]
Finally, sumExtras auto labeling is last.

## Default table without labels
Now, the trial dataset contains variable attributes.
However, let's explicitly add the word "ATTRIBUTE" to the age variable.
This will become more apparent as we continue.
Now, notice in the output on the right, the age has that big attribute.
[CLICK]
The variables marker and grade do not have any nice styled labels, 
and that's because when we initially mutated our data on slide 6, label attributes
were stripped from marker and grade.

## The gtsummary::tbl_* labeling method
Labels set using the label parameter will always override attributes as
they are natively greater in the labeling hierarchy.
This action is native to gtsummary.
[CLICK]
Let's now also set the attribute for marker
[CLICK]
and also add the label parameter label for marker. 
This will highlight the labeling hierarchy concept because notice
the output table. The variable label for marker is "marker label".
[CLICK]
Also, notice the variable grade still has no label since it does not have
a label attribute from the previous mutate nor was any label assigned in the 
tbl_summary function.

## Creating a variable dictionary
We have one final labeling method at our disposal.
Let's create a dictionary object and add a very-visual "DICT" to our variable labels.
[CLICK]
The dictionary requires the variable and description columns.
[CLICK]
The dictionary object can exist with any case-insensitive version of the words
variable and description: lowercase, title case, or uppercase.
This can also be an object you import from Excel. 

## Use the dictionary with add_auto_labels
We will continue with our explicit examples and add parameter labels within
the tbl_summary function. 
I've added "label" here to all the variable labels to stress the understanding
of the labeling hierarchy.
[CLICK]
We then pipe this to add_auto_labels, but nothing changed in our table output.
There aren't any labels with the explicit DICT from the dictionary.
Why? Again, the labels set in the label parameter always take priority.

## Use the dictionary with add_auto_labels part 2
But we actually want the auto-labeling!
[CLICK]
We'll begin by commenting out the label parameter code
so add auto labels can work as intended. 
Notice the output table now has the DICT for grade originating from the dictionary object.
[pause]
If we look closely, age and marker have the label from the attributes we set on
slides 19 & 20.
T stage and the last 3 variables retained the label attributes from the
trial dataset that our dat dataset originated from.
Here we have all 

You'll notice that back here we set the variables with DICT to be very explicit, but you do not notice them here in the output. That is, again, because the label parameter takes priority.

So how can we do this better? Well, first we can strip out the labels. We'll just comment them out here and then again, pass the add auto labels, and you will notice that the age attribute is maintained and the dictionary now appears for grade.

We can use the dictionary with the add auto labels function and set persistent options that maintain through this session. Or you can add this to your R profile if you find yourself frequently using the gtsummary in some extras package. This will reset the hierarchy, so the dictionary now takes precedence.

Okay, we'll be the primary labeling method and you no longer need to use the add auto labels function extras will now add the labels for you. So how do we apply the dictionary? Well simply, so how do we apply our dictionary now? Well, we set our options and now just only pipe to extras. And you'll notice the output on the right.

All of the labels that we have in the dictionary have that DICT afterwards. And this again is to demonstrate what is the hierarchy. So let's add some grouping to our variables.

We will use the gtsummary add variable group header and then just pipe that to add group styling. And what you get right outta the box with this is bold and italicized grouping labels and it restores left justified variable indentation. Well, what does that mean? Prior to using the ad group styling, this T stage would be in line with the factors here.

Um.

We can also add group colors with the add group colors function, and you can use one or you can set a vector of colors that you would like to use. And this is depends on the number of grouping variables that you use. So here we have two groups and we use two specific colors. But do take note that when you use the ad group colors, this will convert the table to a GT table to apply these tweaks.

So this function should be used as the last step within your pipeline. Through this whole process, we've reduced the code. We've removed these labels specifically inside of the table summary function. We've removed these extra gtsummary functions as well. Uh, we applied the some extras clean table, and we've done it all by just applying this one simple extras function.

Our code was cut in half and that was just only for one table, and we still get the same output that we were going for. So what are some other extra parameters that you can set? Well, within this we have some gtsummary Default for P value. True overall, true or last False. So the last argument is for where do we want to position the overall column.

We can also set some, oh shit, this is bad.

So what are some other parameters that we can set within the extras function? Well, gtsummary gives us some defaults. So for P values in the overall column, these are the native defaults. And the last is for where to position that overall column. So when we specify that last equals false, it will put that into the first column position.

Other, some extras options are, what do we want for the header? So you notice that we remove the characteristic from the header. Uh, we've replaced the zeros and NA values in the clean table function with this symbol for the M dash, and we can also pass a ARGs and p ARGs, which we will get to in the next slide.

But the P value overall and last parameters, those come directly from GT summaries, defaults for the add p and add overall functions. Extras can also use a dot ARGs parameter to create reusable default overrides. So for example, we're going to set a list of extra arguments here. So the P value and the position of the overall column are going to be overridden.

Uh, the last equals true now places that overall column into the final position. And then we just take these extra arguments and pass them in the dot ARGs parameter position. We can do the same thing for P value styling. We can customize that using the dot add p ARGs. Okay, so again, we're going to create a list where we specify the test for the continuous variables.

Age and a marker will be the T-test, and we're going to style them with two digits for the output. Again, passing inside the extras function, the dot add P ARGs PRS parameter, some extra supports. Most of the gtsummary tables that you may use with either partial or. Full features available, so please check the documentation for both packages for more specifics, or feel free to reach out to me.

Thank you so much for choosing to spend your time with me today. I really appreciate it. You can find some extras on GitHub at.

And thank you for spending your time with me today. You can find me on GitHub here or email me at kyle@kylegrlist.com. The slides are live and available right now at slides dot kyle gr list.com/some extras. And the package documentation can also be found@kylegrlist.com slash some extras. Thank you so much and enjoy the rest of your conference.